---
title: "Low-quality Cells Validation"
output: html_document
---

```{r global_options, include=FALSE}
library(ggplot2)
library(ggsci)
library(ggpubr)
library(ggrastr)
library(dplyr)
library(parallel)
library(reshape2)
library(RColorBrewer)

source("./Functions/PlotFuncs.R")
source("./Functions/Functions.R")

knitr::opts_chunk$set(fig.width=5, fig.height=3, echo=FALSE, warning=FALSE, message=FALSE)

theme_set(theme_base)

set.seed(42)
kDatasetName <- 'SCG71'

kPlotsFolder <- paste0('/d0-mendel/home/viktor_petukhov/Data/Plots/PaperReview/LowQualityCells/', kDatasetName, '/')
```

```{r}
kDataPath <- '/d0-mendel/home/viktor_petukhov/Data/SCG71/'
holder <- readRDS(paste0(kDataPath, 'est_11_14_poisson_real/SCG71.rds'))
genesets <- readRDS('/d0-mendel/home/viktor_petukhov/cp/data/genesets_mouse.rds')
```

```{r}
est_cell_num <- EstimateCellsNumber(holder$aligned_umis_per_cell)
umis_per_cell <- sort(holder$aligned_umis_per_cell, decreasing=T)
```

```{r}
r_cm_unknown <- holder$cm_raw[, names(sort(holder$aligned_umis_per_cell, decreasing=T))]#[1:est_cell_num$max]]
r_cm_unknown <- r_cm_unknown[Matrix::rowSums(r_cm_unknown > 0) > 10, ]

scores_unknown <- ScorePipelineCells(holder, mitochondrion.genes=genesets$mitochondrion, filter.high.mit.fraction=T, predict.all=T)[colnames(r_cm_unknown)]
PlotCellScores(scores_unknown)
```

```{r}
intersect_cbs <- names(scores_unknown[1:est_cell_num$expected])
intersect_cbs <- intersect_cbs[scores_unknown[intersect_cbs] > 0.5]

unknown_cell_scores <- scores_unknown[(est_cell_num$expected+1):length(scores_unknown)]
rescued_cbs <- names(unknown_cell_scores)[unknown_cell_scores > 0.9]

unknown_cell_scores <- scores_unknown[1:est_cell_num$expected]
filtered_cbs <- names(unknown_cell_scores)[unknown_cell_scores < 0.1]

c(length(intersect_cbs), length(rescued_cbs), length(filtered_cbs))
```

## Seurat analysis
```{r}
r_cm_rescued <- holder$cm_raw[, c(names(umis_per_cell)[1:est_cell_num$expected], rescued_cbs)]
```

```{r, message=FALSE}
library(Seurat)
srt <- CreateSeuratObject(raw.data = r_cm_rescued, min.cells = 10, min.genes = 0, project = "SCG71")
srt <- NormalizeData(object = srt, normalization.method = "LogNormalize", scale.factor = 10000)
srt <- FindVariableGenes(object = srt, mean.function = ExpMean, dispersion.function = LogVMR, 
                         x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 1)
srt <- ScaleData(object = srt, vars.to.regress = "nUMI")
srt <- RunPCA(object = srt, pc.genes = srt@var.genes, do.print = FALSE, pcs.compute=50, maxit=1000, work=500)
srt <- JackStraw(object = srt, num.replicate = 100, do.print = FALSE)
PCElbowPlot(object = srt, num.pc=50)

pcs <- 1:50
srt <- FindClusters(object = srt, reduction.type = "pca", dims.use = pcs, 
                    resolution = 0.6, print.output = 0, save.SNN = TRUE)

srt <- RunTSNE(object = srt, dims.use = pcs, do.fast = TRUE)

save(srt, file = "~/tmp_exchange/scg71_srt.Robj")
```

```{r}
TSNEPlot(object = srt, do.label=T)
```

```{r}
FindClusterMarkers <- function(clust2, clust1, srt.obj, max.pval=1e-5) {
  res <- FindMarkers(object = srt, ident.1 = clust1, ident.2 = clust2, min.pct = 0.25, only.pos=T) %>%
    tibble::rownames_to_column('gene') %>% filter(p_val_adj < 1e-5) %>% .$gene

  return(res)
}

compared_clusters <- unique(srt@ident)
cluster_markers <- mclapply(compared_clusters, function(i) mclapply(setdiff(compared_clusters, i), FindClusterMarkers, i, srt, mc.cores=4), mc.cores=11)
```

```{r}
overexpressed_genes <- Reduce(union, lapply(cluster_markers, function(x) (unlist(x) %>% table() %>% sort(decreasing=T) %>% names())[1:50]))
length(overexpressed_genes)

overexpressed_genes_mask <- lapply(compared_clusters, function(cl) Matrix::rowMeans(srt@data[overexpressed_genes, names(srt@ident)[srt@ident == cl]] > 0) > 0.6)
overexpressed_genes_mask <- Reduce(`|`, overexpressed_genes_mask)
overexpressed_genes <- names(overexpressed_genes_mask)[overexpressed_genes_mask]
length(overexpressed_genes)

clusters_info <- list(clusters=srt@ident, marks=cluster_markers, overexpressed_genes=overexpressed_genes)
saveRDS(clusters_info, '~/tmp_exchange/SCG71_cluster_markers.rds')
```

```{r}
clusters_info <- readRDS('~/tmp_exchange/SCG71_cluster_markers.rds')
```

## Aggregated tSNE plot
```{r, message=FALSE}
r_rescued <- GetPagoda(r_cm_rescued, n.cores=30)
r_rescued$getEmbedding(type='PCA', perplexity=20, embeddingType = 'tSNE', verbose=T, max_iter=10000)
r_rescued$getKnnClusters(method=multilevel.community, type='PCA', name='multilevel')
```

```{r}
PlotPagodaEmbeding(r_rescued, clusters=srt@ident, min.cluster.size=50)
# PlotPagodaEmbeding(r_rescued, clustering.type='multilevel')
PlotPagodaEmbeding(r_rescued, clusters=srt@ident[rescued_cbs])
PlotPagodaEmbeding(r_rescued, clusters=srt@ident[filtered_cbs])
```

```{r}
clusters <- srt@ident
intersect_clusters <- clusters[intersect_cbs]

cluster_centers <- split(names(intersect_clusters), intersect_clusters) %>% 
  lapply(function(cbs) r_rescued$reductions$PCA[cbs, , drop=F] %>% Matrix::colMeans())

rescued_clusters <- apply(r_rescued$reductions$PCA[rescued_cbs, , drop=F], 1, function(cell)
  sapply(cluster_centers, cor, cell) %>% which.max() %>% names() %>% as.integer())

filtered_clusters <- apply(r_rescued$reductions$PCA[filtered_cbs, , drop=F], 1, function(cell)
  sapply(cluster_centers, cor, cell) %>% which.max() %>% names() %>% as.integer())

updated_clusters <- apply(r_rescued$reductions$PCA, 1, function(cell)
  sapply(cluster_centers, cor, cell) %>% which.max() %>% names() %>% as.integer())

clusters <- updated_clusters
intersect_clusters <- clusters[intersect_cbs]
```

```{r}
filt_df <- PlotPagodaEmbeding(r_rescued, clusters=filtered_clusters, return.df=T)
rescued_df <- PlotPagodaEmbeding(r_rescued, clusters=rescued_clusters, return.df=T)

gg <- PlotPagodaEmbeding(r_rescued, clusters=clusters[names(clusters) %>% setdiff(rescued_cbs) %>% setdiff(filtered_cbs)], show.legend=F,
                         mark.clusters=T, alpha=0.5, size=1, font.size=4.5, plot.na=F, min.cluster.size=50)

gg$layers <- c(geom_point(data=filt_df, mapping=aes(x=V1, y=V2, shape='filtered'), size=1), 
               geom_point(data=rescued_df, mapping=aes(x=V1, y=V2, shape='rescued', color=Cluster), size=1.5, alpha=0.9, stroke=0.7), 
               gg$layers)

gg$layers[[3]]$mapping$shape <- 'unchanged'

gg + scale_color_discrete(guide="none") + 
  scale_shape_manual(values=c(4, 24, 19), name='Cells filtration') + 
  theme_pdf(legend.pos=c(1, 1)) +
  scale_size_continuous(range=c(3, 7), trans='identity', guide='none')
```

## Heatmaps
```{r}
tested_clusts <- sort(c(intersect_clusters, rescued_clusters, filtered_clusters))
separation <- c(setNames(rep('rescued', length(rescued_cbs)), rescued_cbs), 
                setNames(rep('real', length(intersect_clusters)), names(intersect_clusters)))

umis_per_cb_subset <- log10(Matrix::colSums(r_cm_unknown[, names(tested_clusts)]))
tested_clusts <- tested_clusts[order(tested_clusts, -umis_per_cb_subset)]

de_genes <- intersect(colnames(r_rescued$counts), clusters_info$overexpressed_genes)

m_subset <- log10(1e-6 + as.matrix(r_rescued$counts[names(tested_clusts), de_genes]))
```

```{r, fig.width=6, fig.height=7}
legendGuide <- function(title, guide=ggplot2::guide_colorbar, ...) {
  guides(fill = guide(title.position='top', direction='horizontal', title=title, barwidth=unit(1.5, 'in'), ...))
}

plot_df <- ExpressionMatrixToDataFrame(m_subset, umis_per_cb_subset, as.factor(tested_clusts), filtration.type=separation)
plot_df <- plot_df %>% filter(UmisPerCb < 3.2) %>% filter(Cluster %in% Reduce(intersect, split(plot_df$Cluster, plot_df$FiltrationType)))
plot_dfs <- split(plot_df, plot_df$FiltrationType)


ggs <- lapply(plot_dfs, HeatmapAnnotGG, umi.per.cell.limits=range(plot_df$UmisPerCb))

gg_legends <- mapply(`+`, ggs$real, list(legendGuide('log10(expression)'), 
                                    legendGuide('Cell type', guide=guide_legend, nrow=3), 
                                    legendGuide('log10(#molecules)')), SIMPLIFY=F) %>%
  lapply(`+`, theme(legend.margin=margin(l=4, r=4, unit='pt'))) %>% lapply(get_legend)

ggs$real$heatmap <- ggs$real$heatmap + rremove('xlab') + ylab('Cells')
ggs$rescued$heatmap <- ggs$rescued$heatmap + labs(x = 'Genes', y = 'Cells')
ggs_annot <- lapply(ggs, function(gg) cowplot::plot_grid(plotlist=lapply(gg, `+`, rremove('legend')), nrow=1, rel_widths=c(1.5, 0.1, 0.1), align='h'))

gg_legends <- cowplot::plot_grid(plotlist=gg_legends, nrow=3, align='v')
```

Rescued cells:
```{r, fig.width=6, fig.height=7}
cowplot::plot_grid(ggs_annot$real, ggs_annot$rescued, nrow=2, labels='AUTO') %>%
  cowplot::plot_grid(gg_legends, rel_widths=c(1, 0.5))

# ggsave(paste0(kPlotsFolder, 'rescued_cells_heatmaps.pdf'), width=6, height=7)
```
