---
title: "10x Aml035 Post"
output:
  html_document:
    df_print: kable
    number_sections: yes
    theme: cerulean
    toc: yes
  html_notebook: default
---
<!-- 
Input:
* raw: list of information about raw data
* umiTrimLength: trimming length
* underestStep: discretization level for collision adjustment
* mcCoresLarge: optional, default 30
* mcCoresSmall: optional, default 7
-->

```{r}
mc_cores_large <- if (exists("mcCoresLarge")) mcCoresLarge else 30
mc_cores_small <- if (exists("mcCoresSmall")) mcCoresSmall else 7

max_neighbours <- umiTrimLength * 3
total_umis_num <- 4**umiTrimLength
```

### Initialization

```{r}

```

```{r}
trimmed$filt_umis_per_gene <- mclapply(trimmed$filt_cells, lapply, sapply, length, mc.cores=mc_cores_small)
trimmed$filt_umis_per_gene_vec <- lapply(trimmed$filt_umis_per_gene, unlist)
trimmed$filt_umis_per_gene_vec_adj <- mclapply(trimmed$filt_umis_per_gene_vec, sapply, GetGeneEstimatedValue, trimmed$underest_sizes$real, trimmed$underest_sizes$estimated, mc.cores=mc_cores_small)

trimmed$umis_per_gene_vec <- unlist(trimmed$umis_per_gene)
```

```{r}
if (any(sapply(trimmed$filt_umis_per_gene, function(x) is.null(names(x)))) | is.null(names(raw$filt_umis_per_gene_simple)))
  stop("Null names")

if (!all(names(trimmed$filt_umis_per_gene$NB) == names(raw$filt_umis_per_gene_simple)))
  stop("names aren't equal 1")

if (!all(names(trimmed$umis_per_gene_vec) == names(trimmed$filt_umis_per_gene_vec$NB)))
  stop("names aren't equal 2")
```
