# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
GetAdjacentUmis <- function(umi) {
    .Call('_dropestr_GetAdjacentUmis', PACKAGE = 'dropestr', umi)
}

GetCrossmergedMask <- function(base_umis, target_umis) {
    .Call('_dropestr_GetCrossmergedMask', PACKAGE = 'dropestr', base_umis, target_umis)
}

ResolveUmiDependencies <- function(base_umis, target_umis, verbose = FALSE) {
    .Call('_dropestr_ResolveUmiDependencies', PACKAGE = 'dropestr', base_umis, target_umis, verbose)
}

SubsetAdjacentUmis <- function(umis) {
    .Call('_dropestr_SubsetAdjacentUmis', PACKAGE = 'dropestr', umis)
}

#' Fill information about adjacent UMIs, their probabilities and differences for each UMI.
#'
#' @param umi_probabilites vector of UMI probabilities.
#' @param adjacent_only logical, return only the list of adjacent UMIs.
#' @param show_progress show progress bar.
#' @return List with the information about adjacent UMIs.
#'
#' @export
FillAdjacentUmisData <- function(umi_probabilites, adjacent_only = FALSE, show_progress = FALSE) {
    .Call('_dropestr_FillAdjacentUmisData', PACKAGE = 'dropestr', umi_probabilites, adjacent_only, show_progress)
}

#' @export
GetAdjacentUmisNum <- function(reads_per_umi_from, reads_per_umi_to) {
    .Call('_dropestr_GetAdjacentUmisNum', PACKAGE = 'dropestr', reads_per_umi_from, reads_per_umi_to)
}

#' @export
FillDpMatrix <- function(prior_prob, neighbours_num, max_umi_per_cell) {
    .Call('_dropestr_FillDpMatrix', PACKAGE = 'dropestr', prior_prob, neighbours_num, max_umi_per_cell)
}

GetSmallerNeighboursDistributionsBySizes <- function(dp_matrices, larger_neighbours_num, neighbour_prob_inds, size_adj, max_neighbour_num, smaller_neighbours_num = integer(), log_probs = FALSE, return_raw = FALSE) {
    .Call('_dropestr_GetSmallerNeighboursDistributionsBySizes', PACKAGE = 'dropestr', dp_matrices, larger_neighbours_num, neighbour_prob_inds, size_adj, max_neighbour_num, smaller_neighbours_num, log_probs, return_raw)
}

FilterUmisInGeneClassic <- function(reads_per_umi, mult = 1) {
    .Call('_dropestr_FilterUmisInGeneClassic', PACKAGE = 'dropestr', reads_per_umi, mult)
}

#' @export
Quantize <- function(values, quant_borders) {
    .Call('_dropestr_Quantize', PACKAGE = 'dropestr', values, quant_borders)
}

ArrangePredictions <- function(target_umi_factors, probs) {
    .Call('_dropestr_ArrangePredictions', PACKAGE = 'dropestr', target_umi_factors, probs)
}

FilterPredictions <- function(not_filtered_umis, base_umis, target_umis) {
    .Call('_dropestr_FilterPredictions', PACKAGE = 'dropestr', not_filtered_umis, base_umis, target_umis)
}

PrepareClassifierData <- function(reads_per_umi) {
    .Call('_dropestr_PrepareClassifierData', PACKAGE = 'dropestr', reads_per_umi)
}

PrepareClassifierTrainingData <- function(reads_per_umi_pairs) {
    .Call('_dropestr_PrepareClassifierTrainingData', PACKAGE = 'dropestr', reads_per_umi_pairs)
}

#' @export
FillCollisionsAdjustmentInfo <- function(umi_probabilities, max_umi_per_gene, verbose = FALSE) {
    .Call('_dropestr_FillCollisionsAdjustmentInfo', PACKAGE = 'dropestr', umi_probabilities, max_umi_per_gene, verbose)
}

#' @export
AdjustGeneExpressionUniform <- function(value, umis_number) {
    .Call('_dropestr_AdjustGeneExpressionUniform', PACKAGE = 'dropestr', value, umis_number)
}

DeadjustGeneExpression <- function(gene_expression, adjusted_expressions) {
    .Call('_dropestr_DeadjustGeneExpression', PACKAGE = 'dropestr', gene_expression, adjusted_expressions)
}

#' @export
ValueCountsC <- function(values) {
    .Call('_dropestr_ValueCountsC', PACKAGE = 'dropestr', values)
}

#' @export
ValueCounts <- function(values, return_probs = FALSE) {
    .Call('_dropestr_ValueCounts', PACKAGE = 'dropestr', values, return_probs)
}

#' @export
BuildCountMatrix <- function(reads_per_umi_per_cell) {
    .Call('_dropestr_BuildCountMatrix', PACKAGE = 'dropestr', reads_per_umi_per_cell)
}

#' @export
TrimUmis <- function(rpu_per_cell, trim_length, reverse = FALSE) {
    .Call('_dropestr_TrimUmis', PACKAGE = 'dropestr', rpu_per_cell, trim_length, reverse)
}

#' Estimate a distribution of observed UMI probabilities.
#'
#' @param umis_per_gene_per_cell list of vectors: number of UMIs per gene per cell (zeros can be omitted).
#' @param umi_length length of UMI.
#' @param smooth smooth term, which is added to each UMI probability in case if some UMIs have only few observations.
#' @return Vector of UMI probabilities.
#' @export
GetUmisDistribution <- function(umis_per_gene_per_cell, smooth = 1L) {
    .Call('_dropestr_GetUmisDistribution', PACKAGE = 'dropestr', umis_per_gene_per_cell, smooth)
}

GetUmisList <- function(umi_len) {
    .Call('_dropestr_GetUmisList', PACKAGE = 'dropestr', umi_len)
}

ConcatLists <- function(lists) {
    .Call('_dropestr_ConcatLists', PACKAGE = 'dropestr', lists)
}

GetMirrorPairs <- function(pairs, probs, tol = 1e-5) {
    .Call('_dropestr_GetMirrorPairs', PACKAGE = 'dropestr', pairs, probs, tol)
}

NumberOfNucleotidePairs <- function() {
    .Call('_dropestr_NumberOfNucleotidePairs', PACKAGE = 'dropestr')
}

